### ISSUE TITLE
是不是我配置有问题,启动提示权限不够

### ISSUE THREAD

**Issue by middddd** [LinShunKang/MyPerf4J#20]
**这个是堆栈异常**

java -javaagent:D:\MyPerf4J\MyPerf4J-ASM.jar -DMyPerf4JPropFile=D:\MyPerf4J\myPerf4J.properties -jar hk8700-1.3.0.jar
2018-11-08 10:01:32.504 [MyPerf4J] WARN profilingParamFile is empty!
2018-11-08 10:01:32.522 [MyPerf4J] INFO
    __  ___      ____            ______ __      __
   /  |/  /_  __/ __ \___  _____/ __/ // /     / /
  / /|_/ / / / / /_/ / _ \/ ___/ /_/ // /___  / /
 / /  / / /_/ / ____/  __/ /  / __/__  __/ /_/ /
/_/  /_/\__, /_/    \___/_/  /_/    /_/  \____/
       /____/

2018-11-08 10:01:32.522 [MyPerf4J] INFO AbstractBootstrap doInitial() SUCCESS!!!
2018-11-08 10:01:32.561 [MyPerf4J] INFO ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/elink/estos/api/bootstrap/Bootstrap8700, classBeingRedefined, protectionDomain, 1332)...
2018-11-08 10:01:32.586 [MyPerf4J] ERROR ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/elink/estos/api/bootstrap/Bootstrap8700, null, ProtectionDomain  (file:/D:/Users/30451/Documents/estos-api4/hk8700/target/hk8700-1.3.0.jar <no signer certificates>)
 sun.misc.Launcher$AppClassLoader@18b4aac2
 <no principals>
 java.security.Permissions@17a7cec2 (
 ("java.io.FilePermission" "\D:\Users\30451\Documents\estos-api4\hk8700\target\hk8700-1.3.0.jar" "read")
 ("java.lang.RuntimePermission" "exitVM")
)

, 1332)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at cn.myperf4j.asm.aop.ProfilingTransformer.getBytes(ProfilingTransformer.java:54)
        at cn.myperf4j.asm.aop.ProfilingTransformer.transform(ProfilingTransformer.java:37)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2018-11-08 10:01:32.693 [MyPerf4J] INFO ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/elink/common/utils/PropertiesLoader, classBeingRedefined, protectionDomain, 5941)...
2018-11-08 10:01:32.695 [MyPerf4J] ERROR ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/elink/common/utils/PropertiesLoader, null, ProtectionDomain  (file:/D:/Users/30451/Documents/estos-api4/hk8700/target/hk8700-1.3.0.jar <no signer certificates>)
 sun.misc.Launcher$AppClassLoader@18b4aac2
 <no principals>
 java.security.Permissions@17a7cec2 (
 ("java.io.FilePermission" "\D:\Users\30451\Documents\estos-api4\hk8700\target\hk8700-1.3.0.jar" "read")
 ("java.lang.RuntimePermission" "exitVM")
)

, 5941)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at cn.myperf4j.asm.aop.ProfilingTransformer.getBytes(ProfilingTransformer.java:54)
        at cn.myperf4j.asm.aop.ProfilingTransformer.transform(ProfilingTransformer.java:37)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.elink.estos.api.bootstrap.Bootstrap8700.<clinit>(Bootstrap8700.java:22)
start hk8700 server
2018-11-08 10:01:32.736 [MyPerf4J] INFO ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/elink/common/utils/FileUtils, classBeingRedefined, protectionDomain, 14416)...
2018-11-08 10:01:32.737 [MyPerf4J] ERROR ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/elink/common/utils/FileUtils, null, ProtectionDomain  (file:/D:/Users/30451/Documents/estos-api4/hk8700/target/hk8700-1.3.0.jar <no signer certificates>)
 sun.misc.Launcher$AppClassLoader@18b4aac2
 <no principals>
 java.security.Permissions@17a7cec2 (
 ("java.io.FilePermission" "\D:\Users\30451\Documents\estos-api4\hk8700\target\hk8700-1.3.0.jar" "read")
 ("java.lang.RuntimePermission" "exitVM")
)

, 14416)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at cn.myperf4j.asm.aop.ProfilingTransformer.getBytes(ProfilingTransformer.java:54)
        at cn.myperf4j.asm.aop.ProfilingTransformer.transform(ProfilingTransformer.java:37)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.elink.estos.api.bootstrap.Bootstrap8700.main(Bootstrap8700.java:28)

**配置文件信息**

#应用名称
AppName=MyPerf4JTest

#MetricsProcessor类型，0:以标准格式化结构输出到stdout.log 1:以标准格式化结构输出到磁盘  2:以InfluxDB LineProtocol格式输出到磁盘
MetricsProcessorType=1

#配置各个Metrics日志的文件路径，可不配置
MethodMetricsFile=D:\\MyPerf4J\\method_metrics.log
#ClassMetricsFile=/data/logs/MyPerf4J/class_metrics.log
#GCMetricsFile=/data/logs/MyPerf4J/gc_metrics.log
#MemMetricsFile=/data/logs/MyPerf4J/memory_metrics.log
ThreadMetricsFile=D:\\MyPerf4J\\thread_metrics.log

#配置日志文件滚动时间间隔，分别有MINUTELY、HOURLY和DAILY三个值
LogRollingTimeUnit=HOURLY
   
#配置备份Recorders的数量，默认为1，最小为1，最大为8，当需要在较小MillTimeSlice内统计大量方法性能数据时可配置大一些
BackupRecordersCount=1
   
#配置Record模式，可配置为accurate/rough
RecorderMode=accurate
   
#配置时间片，单位为ms，最小1s，最大600s
MilliTimeSlice=10000

#是否展示方法参数类型
ShowMethodParams=true
   
#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=com.elink
   
#不需要监控的package，可配置多个，用英文';'分隔
ExcludePackages=org.spring;
   
#可配置多个方法名，用英文';'分隔
ExcludeMethods=equals;hash
   
#是否排除私有方法，true/false
ExcludePrivateMethod=true
   
#通用的方法执行时间阈值，单位为ms
ProfilingTimeThreshold=1000
   
#在一个时间片内，超过方法执行时间阈值的次数，仅在RecorderMode=accurate时有效
ProfilingOutThresholdCount=10

**Comment by ThinkpadNC5** [comment]
请问，你这个是什么类型的应用？

**Comment by middddd** [comment]
普通的Maven项目集成了spring框架 spring扫描类后 启动了Netty

**Comment by ThinkpadNC5** [comment]
建议先缩小 `IncludePackages` 的范围

**Comment by middddd** [comment]
缩小到最小范围了

2018-11-12 15:50:26.805 [MyPerf4J] INFO AutoRollingFileWriter.rollingFile(Mon Nov 12 15:50:26 CST 2018): rename D:\MyPerf4J\method_metrics.log to method_metrics.log.2018-11-12-14 true
2018-11-12 15:50:26.805 [MyPerf4J] WARN profilingParamFile is empty!
2018-11-12 15:50:26.836 [MyPerf4J] INFO AutoRollingFileWriter.rollingFile(Mon Nov 12 15:50:26 CST 2018): rename D:\MyPerf4J\thread_metrics.log to thread_metrics.log.2018-11-12-14 true
2018-11-12 15:50:26.852 [MyPerf4J] INFO 
    __  ___      ____            ______ __      __
   /  |/  /_  __/ __ \___  _____/ __/ // /     / /
  / /|_/ / / / / /_/ / _ \/ ___/ /_/ // /___  / / 
 / /  / / /_/ / ____/  __/ /  / __/__  __/ /_/ /  
/_/  /_/\__, /_/    \___/_/  /_/    /_/  \____/   
       /____/                                     

2018-11-12 15:50:26.852 [MyPerf4J] INFO AbstractBootstrap doInitial() SUCCESS!!!
start hk8700 server
Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@35851384: startup date [Mon Nov 12 15:50:27 CST 2018]; root of context hierarchy
Loading XML bean definitions from class path resource [spring.xml]
2018-11-12 15:50:27.596 [MyPerf4J] INFO ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/estos/api/third/service/impl/CardServiceImpl, classBeingRedefined, protectionDomain, 6036)...
2018-11-12 15:50:27.596 [MyPerf4J] ERROR ProfilingTransformer.transform(sun.misc.Launcher$AppClassLoader@18b4aac2, com/estos/api/third/service/impl/CardServiceImpl, null, ProtectionDomain  (file:/D:/Users/30451/Documents/estos-api4/hk8700/target/classes/ <no signer certificates>)
 sun.misc.Launcher$AppClassLoader@18b4aac2
 <no principals>
 java.security.Permissions@3444d69d (
 ("java.io.FilePermission" "\D:\Users\30451\Documents\estos-api4\hk8700\target\classes\-" "read")
 ("java.lang.RuntimePermission" "exitVM")
)

, 6036)
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at cn.myperf4j.asm.aop.ProfilingTransformer.getBytes(ProfilingTransformer.java:54)
	at cn.myperf4j.asm.aop.ProfilingTransformer.transform(ProfilingTransformer.java:37)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:83)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)

**Comment by ThinkpadNC5** [comment]
应该不是权限问题，根据你的异常栈和 ASM 代码，怀疑是 JDK 版本号不支持导致的；
请问你的 JDK 版本号是多少？根据ASM的代码逻辑，ASM目前支持到 JDK 12 了。

PS：请 pull develop 分支的代码，重新打包

**Comment by zmr518** [comment]
参数加到jvm启动参数中启动不了，求解
export JAVA_OPTS=“-javaagent:/tmp/MyPerf4J/MyPerf4J-ASM.jar -DMyPerf4JPropFile=/tmp/MyPerf4J/myPerf4J.properties”

**Comment by middddd** [comment]
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
这是我JDK的版本号

**Comment by ThinkpadNC5** [comment]
你好，请确认一下你的项目是否依赖了低版本的 asm，如果是的话，可以修改 MyPerf4J 中 asm 的版本号以适配你的项目
