### ISSUE TITLE
直接使用下载的MyPerf4J-ASM.jar,出现java.lang.TypeNotPresentException

### ISSUE THREAD

**Issue by zhangyuwei1979** [LinShunKang/MyPerf4J#36]
环境
centos7.2
jdk1.8
tomcat8.5.39
异常
2019-03-29 17:47:21.689 [MyPerf4J] ERROR ProfilingTransformer.transform(ParallelWebappClassLoader^M
  context: system^M
  delegate: false^M
----------> Parent Classloader:^M
java.net.URLClassLoader@3581c5f3^M
, org/apache/xerces/impl/Constants, null, protectionDomain, 8957) Type org/apache/xerces/impl/Constants$ArrayEnumeration not present
java.lang.TypeNotPresentException: Type org/apache/xerces/impl/Constants$ArrayEnumeration not present
        at org.shaded.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:951)
        at org.shaded.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1209)
        at org.shaded.objectweb.asm.Frame.merge(Frame.java:1293)
        at org.shaded.objectweb.asm.Frame.merge(Frame.java:1238)
        at org.shaded.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1613)
        at org.shaded.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1549)
        at org.shaded.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
        at org.shaded.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(LocalVariablesSorter.java:148)
        at org.shaded.objectweb.asm.ClassReader.readCode(ClassReader.java:2429)
        at org.shaded.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
        at org.shaded.objectweb.asm.ClassReader.accept(ClassReader.java:679)
        at org.shaded.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at cn.myperf4j.asm.aop.ProfilingTransformer.getBytes(ProfilingTransformer.java:57)
        at cn.myperf4j.asm.aop.ProfilingTransformer.transform(ProfilingTransformer.java:37)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2401)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:859)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.validate(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.handleStartElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl$ContentDispatcher.scanRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)

**Comment by LinShunKang** [comment]
你好，请尝试一下这个 jar 包：[MyPerf4J-ASM.jar](https://github.com/LinShunKang/Objects/blob/master/jars/MyPerf4J-ASM-ParallelWebappClassLoader.jar?raw=true)
